version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  ApplicationStart:
    - location: runPy.sh
      timeout: 30000
      runas: ubuntu

permissions:
  - object: runPy.sh
    pattern: "**"
    mode: 777
    type:
      - file