version: 0.0
os: linux
files:
  - source: MainPage.py
    destination: MainPage.py
  - source: /
    destination: /

hooks:
  ApplicationStart:
    - location: MainPage.py
      timeout: 30000
      runas: root

permissions:
  - object: MainPage.py
    pattern: "**"
    mode: 777
    type:
      - file